### ISSUE TITLE
Feature requests - Prevent dupe / Custom sound / Blacklist / Timestamp xx ago

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Keyword-Notifier#1]
It would be nice if it wouldnt detect a duplicate whisper (and open a new tab for it) after you closed the first one (since you cannot set certain keywords as overrides to the detections, and having to close all the false positives can be tricky).

It would also be very nice if there was a timestamp for when the tab had opened.

Also, as it appears that I have strongly favored one of the beeps in mercury trade overseer that is the same as one you have set to whisper notice (I really dont like either of the other remaining options they have), it would be nice to have a few different beeps to choose from here.

**Comment by lemasato** [comment]
Yup. Preventing duplicates is logical and will definitely be added.
Also, maybe a small button to disable the profile directly from the main interface (without having to go in the settings) would be pretty nice too.
Timestamps is a nice small qol, I don't see why it wouldn't be added, thanks for the suggestions!

**Comment by sclient** [comment]
I just noticed it hits on my own whispers as well.

**Comment by sclient** [comment]
Actually, yeah, if there was a button that would turn red that would make it ignore tells until further entry to remove all the whispers it will see while you are in a master party would work well.

**Comment by sclient** [comment]
If there was a way to have it attempt to create a filter based on a certain word in a whisper on the whisper tell, that would be really handy for adding filter exceptions that get through. Like youd click the filter button, and itd pop up all the words in the whisper and you could click one to blacklist it, that would be amazing.

**Comment by lemasato** [comment]
The client logs doesn't show anything about parties/friend invite/guild/etc.  
It's mostly only about area joined, and chat messages.

>youd click the filter button, and itd pop up all the words in the whisper and you could click one to blacklist it

Going into the settings and blacklisting that word would do the same, in just as much time.  
In my opinion, this wouldn't really be necessary.

**Comment by sclient** [comment]
How can you set a word to not hit, ! or something? I need to set some exceptions for my hits.

**Comment by sclient** [comment]
Also, Im thinking for the timestamp, maybe in both of your tools it would be nice if there was an option to have it actually show the time elapsed since the global/whisper spam. That would be seriously helpful!

**Comment by lemasato** [comment]
> How can you set a word to not hit, ! or something? I need to set some exceptions for my hits.
Currently? You can't.

> timestamp show the time elapsed 
Yeah, probably upon hovering the time stamp.

**Comment by lemasato** [comment]
Some of these have been added on [0.3.2](https://github.com/lemasato/POE-Keyword-Notifier/releases/tag/0.3.2), the others will most likely have to wait until next major update.
Thank you for your testings!

**Comment by sclient** [comment]
And thanks back for the tool! Way better than my prior options! ;)

**Comment by melink14** [comment]
+1 on having a way to exclude keywords.
