### ISSUE TITLE
Feature request: Built-in update checking.

### ISSUE THREAD

**Issue by sclient** [lemasato/POE-Keyword-Notifier#6]
nm

**Comment by lemasato** [comment]
There already is actually.
On app start, if an update is detected, it will download it automatically.
I will add a tray menu to check for update though, as automatically update checks can only happen once every 35 minutes to avoid spamming the Github API.

**Comment by lemasato** [comment]
Added the tray option in [0.3.2](https://github.com/lemasato/POE-Keyword-Notifier/releases/tag/0.3.2).
